[tox]
isolated_build = True
envlist = flake8, coverage, pytest, docs
skip_missing_interpreters = True

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry run python -V
    poetry install --no-root --sync --with test,lint
commands =
    poetry run flake8
    poetry run coverage run -m unittest discover --buffer -vv
    poetry run coverage report
    poetry run coverage html

[testenv:{,py311-,py312-,py313-}coverage]

description = Run unittests and coverage analysis.
commands_pre =
    poetry run python -V
    poetry install --no-root --sync --with test
commands =
    poetry run coverage run -m unittest discover --buffer -vv
    poetry run coverage report
    poetry run coverage html

[testenv:pytest]
description = Run synthetic CLI workflow scenarios.
commands_pre =
    poetry run python -V
    poetry install --no-root --sync --with test
commands =
    poetry run pytest -q

[coverage:run]
branch = True
source_pkgs =
    stack_usage_check

[coverage:report]
skip_empty = true
omit =
    */__main__.py
exclude_lines =
    if __name__ == .__main__.:
fail_under=95

[coverage:html]
directory = cover

[testenv:{,py311-,py312-,py313-}flake8]
description = Run linting checks.
commands_pre =
    poetry run python -V
    poetry install --no-root --sync --with lint
commands =
    poetry run flake8

[flake8]
exclude =
    .git,
    __pycache__,
    *.pyc,
    .cache,
    .tox,
    .venv
per-file-ignores =
    # Imported but not used
    __init__.py: F401
max-line-length = 120

[testenv:docs]
description = Generate Python package documentation.
commands_pre =
    poetry install --with docs
commands =
    poetry run sphinx-apidoc -f -o {toxinidir}/doc {toxinidir}/src --module-first
    poetry run sphinx-build -E -W -d  html {toxinidir}/doc/ {toxinidir}/doc/build/html/ --keep-going
