import re

from dataclasses import dataclass
from pathlib import Path


@dataclass
class StackUsageVariables:
    """ Class that represents stack usage data variables from an .su file"""
    function_name: str = None
    stack_usage: int = 0
    type: str = None


@dataclass
class StackUsageList:
    file_path: Path
    su_list: list[StackUsageVariables]


class GccStackUsageFileParser():
    def get_su_data(self, su_file: Path) -> list:
        """ This method will parse the .su (stack usage) file.

        The .su file is generated by GCC during linking process and
        typically contains data of a function's stack usage with this format:

        <file>:<line>:<function>:<stack_usage> <type>
        e.g. BattProfCfgSafe_swc.c:46:6:Run_BattProfCfgSafe_Step	1288	static

        Reference:
        https://gcc.gnu.org/onlinedocs/gnat_ugn/Static-Stack-Usage-Analysis.html

        Args:
            su_file (str): The path to the .su file.

        Returns:
            list: List of StackUsageVariables object.
        """
        result = StackUsageList(file_path=su_file, su_list=[])
        content = su_file.read_text().splitlines()
        for line in content:
            item = StackUsageVariables
            parts = line.split(':')
            if len(parts) == 4:
                func_su_data = parts[3].split()
                result.su_list.append(item(function_name=func_su_data[0],
                                           stack_usage=int(func_su_data[1]),
                                           type=func_su_data[2]))
        return result

    def get_runnable_info(self, su_file: Path) -> StackUsageVariables:
        raw_list = self.get_su_data(su_file)
        runnable_name_search_pattern = re.compile(r'.*_Step.*')

        for item in raw_list.su_list:
            if runnable_name_search_pattern.search(item.function_name):
                return item
            else:
                return None

    def get_all_runnables(self, build_obj_dir: Path) -> list:
        result = []
        for su_file in build_obj_dir.glob('*.su'):
            runnable = self.get_runnable_info(su_file)
            if runnable:
                result.append(runnable)
        return result


class OtherStackUsageFileParser():
    def su_file_parser(self, map_file: Path) -> list:
        pass


class StackUsageFile():
    def StackUsageFileType(type: str):
        stack_usage_info_from_file = {"gcc": GccStackUsageFileParser,
                                      "other_su": OtherStackUsageFileParser}
        return stack_usage_info_from_file[type]()
